{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lexum.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lexum.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range .Values.secrets }}
  {{ .secretKey }}: {{ .value | quote }}
{{- end }}
{{- end }}

