apiVersion: v1
kind: Service
metadata:
  name: lexum-headless
  namespace: lexum
  labels:
    app: lexum-search-engine
spec:
  clusterIP: None
  selector:
    app: lexum-search-engine
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 17300
      targetPort: 17300

