{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lexum.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lexum.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "lexum.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.headlessService.port }}
      targetPort: http
    - name: transport
      port: {{ .Values.network.transportPort }}
      targetPort: transport
{{- end }}

